import {
  AiOutlinePlus as Add,
  AiOutlineArrowLeft as Back,
  AiOutlineCalendar as Calendar,
  AiOutlineCheck as Check,
  AiOutlineCheckSquare as CheckSquare,
  AiOutlineClose as Close,
  AiOutlineCloseSquare as CloseSquare,
  AiOutlineComment as Comment,
  AiOutlineContacts as Contact,
  AiOutlineCopyright as Copyright,
  AiOutlineCrown as Crown,
  AiOutlineDashboard as Dashboard,
  AiOutlineDelete as Delete,
  AiOutlineDown as Down,
  AiOutlineEdit as Edit,
  AiOutlineFilter as Filter,
  AiOutlineFlag as Flag,
  AiOutlineRight as Forward,
  AiOutlineHistory as History,
  AiOutlineHome as Home,
  AiOutlineIdcard as Idcard,
  AiOutlineInfoCircle as Info,
  AiOutlineEyeInvisible as Invisible,
  AiOutlineLink as Link,
  AiOutlineLoading as Loading,
  AiOutlineLock as Lock,
  AiOutlineLogin as Login,
  AiOutlineLogout as Logout,
  AiOutlineMoon as Moon,
  AiOutlineNumber as Number,
  AiOutlineExport as Open,
  AiOutlineRead as Openbook,
  AiOutlinePaperClip as Paperclip,
  AiOutlineQuestion as Question,
  AiOutlineReload as Refresh,
  AiOutlineSave as Save,
  AiOutlineBank as School,
  AiOutlineSearch as Search,
  AiOutlineSetting as Settings,
  AiOutlineSun as Sun,
  AiOutlineTeam as Team,
  AiOutlineTrophy as Trophy,
  AiOutlineUnlock as Unlock,
  AiOutlineUp as Up,
  AiOutlineUser as User,
  AiOutlineUserAdd as UserAdd,
  AiOutlineUserDelete as UserDelete,
  AiOutlineUsergroupAdd as UsergroupAdd,
  AiOutlineUsergroupDelete as UsergroupDelete,
  AiOutlineEye as Visible,
  AiOutlineWarning as Warning,
} from "react-icons/ai";

const iconComponents = {
  add: Add,
  back: Back,
  calendar: Calendar,
  check: Check,
  checkSquare: CheckSquare,
  close: Close,
  closeSquare: CloseSquare,
  comment: Comment,
  contact: Contact,
  copyright: Copyright,
  crown: Crown,
  dashboard: Dashboard,
  delete: Delete,
  down: Down,
  edit: Edit,
  filter: Filter,
  flag: Flag,
  forward: Forward,
  history: History,
  home: Home,
  idcard: Idcard,
  info: Info,
  invisible: Invisible,
  link: Link,
  loading: Loading,
  lock: Lock,
  login: Login,
  logout: Logout,
  moon: Moon,
  number: Number,
  open: Open,
  openbook: Openbook,
  paperclip: Paperclip,
  question: Question,
  refresh: Refresh,
  save: Save,
  school: School,
  search: Search,
  settings: Settings,
  sun: Sun,
  team: Team,
  trophy: Trophy,
  unlock: Unlock,
  up: Up,
  user: User,
  userAdd: UserAdd,
  userDelete: UserDelete,
  usergroupAdd: UsergroupAdd,
  usergroupDelete: UsergroupDelete,
  visible: Visible,
  warning: Warning,
};

export default iconComponents;
