// src/utils/icons.js
import {
  PlusOutlined,
  LeftOutlined,
  CalendarOutlined,
  CheckOutlined,
  CloseOutlined,
  CommentOutlined,
  CopyrightOutlined,
  CrownOutlined,
  DashboardOutlined,
  DeleteOutlined,
  EditOutlined,
  FilterOutlined,
  FlagOutlined,
  RightOutlined,
  HistoryOutlined,
  HomeOutlined,
  IdcardOutlined,
  InfoCircleOutlined,
  EyeInvisibleOutlined,
  LinkOutlined,
  LoadingOutlined,
  LockOutlined,
  MenuOutlined,
  MoonOutlined,
  MoreOutlined,
  NumberOutlined,
  PaperClipOutlined,
  QuestionOutlined,
  ReloadOutlined,
  SaveOutlined,
  SearchOutlined,
  SettingOutlined,
  SunOutlined,
  TrophyOutlined,
  UnlockOutlined,
  UserOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  EyeOutlined,
  WarningOutlined,
} from "@ant-design/icons";

// Map icon names to Ant Design icon components
const iconComponents = {
  add: PlusOutlined,
  back: LeftOutlined,
  calendar: CalendarOutlined,
  check: CheckOutlined,
  close: CloseOutlined,
  comment: CommentOutlined,
  copyright: CopyrightOutlined,
  crown: CrownOutlined,
  dashboard: DashboardOutlined,
  delete: DeleteOutlined,
  edit: EditOutlined,
  filter: FilterOutlined,
  flag: FlagOutlined,
  forward: RightOutlined,
  history: HistoryOutlined,
  home: HomeOutlined,
  idcard: IdcardOutlined,
  info: InfoCircleOutlined,
  invisible: EyeInvisibleOutlined,
  link: LinkOutlined,
  loading: LoadingOutlined,
  lock: LockOutlined,
  menu: MenuOutlined,
  moon: MoonOutlined,
  more: MoreOutlined,
  number: NumberOutlined,
  paperclip: PaperClipOutlined,
  question: QuestionOutlined,
  refresh: ReloadOutlined,
  save: SaveOutlined,
  search: SearchOutlined,
  settings: SettingOutlined,
  sun: SunOutlined,
  trophy: TrophyOutlined,
  unlock: UnlockOutlined,
  user: UserOutlined,
  userAdd: UserAddOutlined,
  userDelete: UserDeleteOutlined,
  usergroupAdd: UsergroupAddOutlined,
  usergroupDelete: UsergroupDeleteOutlined,
  visible: EyeOutlined,
  warning: WarningOutlined,
};

export default iconComponents;
